build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Production Owner"
    email: "Aishwarya@eazybnk.com"
  onCallSupport:
    - (453)265-3765
    - (236)734-8371